// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// ==============================================================

extern int assign_intensity (
const unsigned int alphabuf[4][4],
unsigned short intensity,
unsigned int node_output[4][4],
unsigned int node_count[4][4]);
