// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// ==============================================================

#include <systemc>
#include <iostream>
#include <cstdlib>
#include <cstddef>
#include <stdint.h>
#include "SysCFileHandler.h"
#include "ap_int.h"
#include "ap_fixed.h"
#include <complex>
#include <stdbool.h>
#include "autopilot_cbe.h"
#include "ap_stream.h"
#include "hls_stream.h"
#include "hls_half.h"
#include "hls_signal_handler.h"

using namespace std;
using namespace sc_core;
using namespace sc_dt;


// [dump_struct_tree [build_nameSpaceTree] dumpedStructList] ---------->


// [dump_enumeration [get_enumeration_list]] ---------->


// wrapc file define: "alphabuf"
#define AUTOTB_TVIN_alphabuf  "../tv/cdatafile/c.assign_intensity.autotvin_alphabuf.dat"
// wrapc file define: "intensity"
#define AUTOTB_TVIN_intensity  "../tv/cdatafile/c.assign_intensity.autotvin_intensity.dat"
// wrapc file define: "node_output"
#define AUTOTB_TVIN_node_output  "../tv/cdatafile/c.assign_intensity.autotvin_node_output.dat"
#define AUTOTB_TVOUT_node_output  "../tv/cdatafile/c.assign_intensity.autotvout_node_output.dat"
// wrapc file define: "node_count"
#define AUTOTB_TVIN_node_count  "../tv/cdatafile/c.assign_intensity.autotvin_node_count.dat"
#define AUTOTB_TVOUT_node_count  "../tv/cdatafile/c.assign_intensity.autotvout_node_count.dat"
// wrapc file define: "ap_return"
#define AUTOTB_TVOUT_ap_return  "../tv/cdatafile/c.assign_intensity.autotvout_ap_return.dat"

#define INTER_TCL  "../tv/cdatafile/ref.tcl"

// tvout file define: "node_output"
#define AUTOTB_TVOUT_PC_node_output  "../tv/rtldatafile/rtl.assign_intensity.autotvout_node_output.dat"
// tvout file define: "node_count"
#define AUTOTB_TVOUT_PC_node_count  "../tv/rtldatafile/rtl.assign_intensity.autotvout_node_count.dat"
// tvout file define: "ap_return"
#define AUTOTB_TVOUT_PC_ap_return  "../tv/rtldatafile/rtl.assign_intensity.autotvout_ap_return.dat"

class INTER_TCL_FILE {
	public:
		INTER_TCL_FILE(const char* name) {
			mName = name;
			alphabuf_depth = 0;
			intensity_depth = 0;
			node_output_depth = 0;
			node_count_depth = 0;
			ap_return_depth = 0;
			trans_num =0;
		}

		~INTER_TCL_FILE() {
			mFile.open(mName);
			if (!mFile.good()) {
				cout << "Failed to open file ref.tcl" << endl;
				exit (1);
			}
			string total_list = get_depth_list();
			mFile << "set depth_list {\n";
			mFile << total_list;
			mFile << "}\n";
			mFile << "set trans_num "<<trans_num<<endl;
			mFile.close();
		}

		string get_depth_list () {
			stringstream total_list;
			total_list << "{alphabuf " << alphabuf_depth << "}\n";
			total_list << "{intensity " << intensity_depth << "}\n";
			total_list << "{node_output " << node_output_depth << "}\n";
			total_list << "{node_count " << node_count_depth << "}\n";
			total_list << "{ap_return " << ap_return_depth << "}\n";
			return total_list.str();
		}

		void set_num (int num , int* class_num) {
			(*class_num) = (*class_num) > num ? (*class_num) : num;
		}
	public:
		int alphabuf_depth;
		int intensity_depth;
		int node_output_depth;
		int node_count_depth;
		int ap_return_depth;
		int trans_num;

	private:
		ofstream mFile;
		const char* mName;
};


#define assign_intensity AESL_ORIG_DUT_assign_intensity
extern int assign_intensity (
const unsigned int alphabuf[4][4],
unsigned short intensity,
unsigned int node_output[4][4],
unsigned int node_count[4][4]);
#undef assign_intensity

int assign_intensity (
const unsigned int alphabuf[4][4],
unsigned short intensity,
unsigned int node_output[4][4],
unsigned int node_count[4][4])
{
	refine_signal_handler();
	fstream wrapc_switch_file_token;
	wrapc_switch_file_token.open(".hls_cosim_wrapc_switch.log");
	int AESL_i;
	if (wrapc_switch_file_token.good())
	{
		CodeState = ENTER_WRAPC_PC;
		static unsigned AESL_transaction_pc = 0;
		string AESL_token;
		string AESL_num;
		static AESL_FILE_HANDLER aesl_fh;

		int AESL_return;

		// output port post check: "node_output"
		aesl_fh.read(AUTOTB_TVOUT_PC_node_output, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_node_output, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_node_output, AESL_token); // data

			sc_bv<32> *node_output_pc_buffer = new sc_bv<32>[16];
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'node_output', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'node_output', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					node_output_pc_buffer[i] = AESL_token.c_str();
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_node_output, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_node_output))
				{
					exit(1);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: node_output
				{
					// bitslice(31, 0)
					// {
						// celement: node_output(31, 0)
						// {
							sc_lv<32>* node_output_lv0_0_3_1_lv1_0_3_1 = new sc_lv<32>[16];
						// }
					// }

					// bitslice(31, 0)
					{
						int hls_map_index = 0;
						// celement: node_output(31, 0)
						{
							// carray: (0) => (3) @ (1)
							for (int i_0 = 0; i_0 <= 3; i_0 += 1)
							{
								// carray: (0) => (3) @ (1)
								for (int i_1 = 0; i_1 <= 3; i_1 += 1)
								{
									if (&(node_output[0][0]) != NULL) // check the null address if the c port is array or others
									{
										node_output_lv0_0_3_1_lv1_0_3_1[hls_map_index++].range(31, 0) = sc_bv<32>(node_output_pc_buffer[hls_map_index].range(31, 0));
									}
								}
							}
						}
					}

					// bitslice(31, 0)
					{
						int hls_map_index = 0;
						// celement: node_output(31, 0)
						{
							// carray: (0) => (3) @ (1)
							for (int i_0 = 0; i_0 <= 3; i_0 += 1)
							{
								// carray: (0) => (3) @ (1)
								for (int i_1 = 0; i_1 <= 3; i_1 += 1)
								{
									// sub                    : i_0 i_1
									// ori_name               : node_output[i_0][i_1]
									// sub_1st_elem           : 0 0
									// ori_name_1st_elem      : node_output[0][0]
									// output_left_conversion : node_output[i_0][i_1]
									// output_type_conversion : (node_output_lv0_0_3_1_lv1_0_3_1[hls_map_index++]).to_uint64()
									if (&(node_output[0][0]) != NULL) // check the null address if the c port is array or others
									{
										node_output[i_0][i_1] = (node_output_lv0_0_3_1_lv1_0_3_1[hls_map_index++]).to_uint64();
									}
								}
							}
						}
					}
				}
			}

			// release memory allocation
			delete [] node_output_pc_buffer;
		}

		// output port post check: "node_count"
		aesl_fh.read(AUTOTB_TVOUT_PC_node_count, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_node_count, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_node_count, AESL_token); // data

			sc_bv<32> *node_count_pc_buffer = new sc_bv<32>[16];
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'node_count', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'node_count', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					node_count_pc_buffer[i] = AESL_token.c_str();
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_node_count, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_node_count))
				{
					exit(1);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: node_count
				{
					// bitslice(31, 0)
					// {
						// celement: node_count(31, 0)
						// {
							sc_lv<32>* node_count_lv0_0_3_1_lv1_0_3_1 = new sc_lv<32>[16];
						// }
					// }

					// bitslice(31, 0)
					{
						int hls_map_index = 0;
						// celement: node_count(31, 0)
						{
							// carray: (0) => (3) @ (1)
							for (int i_0 = 0; i_0 <= 3; i_0 += 1)
							{
								// carray: (0) => (3) @ (1)
								for (int i_1 = 0; i_1 <= 3; i_1 += 1)
								{
									if (&(node_count[0][0]) != NULL) // check the null address if the c port is array or others
									{
										node_count_lv0_0_3_1_lv1_0_3_1[hls_map_index++].range(31, 0) = sc_bv<32>(node_count_pc_buffer[hls_map_index].range(31, 0));
									}
								}
							}
						}
					}

					// bitslice(31, 0)
					{
						int hls_map_index = 0;
						// celement: node_count(31, 0)
						{
							// carray: (0) => (3) @ (1)
							for (int i_0 = 0; i_0 <= 3; i_0 += 1)
							{
								// carray: (0) => (3) @ (1)
								for (int i_1 = 0; i_1 <= 3; i_1 += 1)
								{
									// sub                    : i_0 i_1
									// ori_name               : node_count[i_0][i_1]
									// sub_1st_elem           : 0 0
									// ori_name_1st_elem      : node_count[0][0]
									// output_left_conversion : node_count[i_0][i_1]
									// output_type_conversion : (node_count_lv0_0_3_1_lv1_0_3_1[hls_map_index++]).to_uint64()
									if (&(node_count[0][0]) != NULL) // check the null address if the c port is array or others
									{
										node_count[i_0][i_1] = (node_count_lv0_0_3_1_lv1_0_3_1[hls_map_index++]).to_uint64();
									}
								}
							}
						}
					}
				}
			}

			// release memory allocation
			delete [] node_count_pc_buffer;
		}

		// output port post check: "ap_return"
		aesl_fh.read(AUTOTB_TVOUT_PC_ap_return, AESL_token); // [[transaction]]
		if (AESL_token != "[[transaction]]")
		{
			exit(1);
		}
		aesl_fh.read(AUTOTB_TVOUT_PC_ap_return, AESL_num); // transaction number

		if (atoi(AESL_num.c_str()) == AESL_transaction_pc)
		{
			aesl_fh.read(AUTOTB_TVOUT_PC_ap_return, AESL_token); // data

			sc_bv<32> ap_return_pc_buffer;
			int i = 0;

			while (AESL_token != "[[/transaction]]")
			{
				bool no_x = false;
				bool err = false;

				// search and replace 'X' with "0" from the 1st char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('X');
					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'ap_return', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				no_x = false;

				// search and replace 'x' with "0" from the 3rd char of token
				while (!no_x)
				{
					size_t x_found = AESL_token.find('x', 2);

					if (x_found != string::npos)
					{
						if (!err)
						{
							cerr << "WARNING: [SIM 212-201] RTL produces unknown value 'X' on port 'ap_return', possible cause: There are uninitialized variables in the C design." << endl;
							err = true;
						}
						AESL_token.replace(x_found, 1, "0");
					}
					else
					{
						no_x = true;
					}
				}

				// push token into output port buffer
				if (AESL_token != "")
				{
					ap_return_pc_buffer = AESL_token.c_str();
					i++;
				}

				aesl_fh.read(AUTOTB_TVOUT_PC_ap_return, AESL_token); // data or [[/transaction]]

				if (AESL_token == "[[[/runtime]]]" || aesl_fh.eof(AUTOTB_TVOUT_PC_ap_return))
				{
					exit(1);
				}
			}

			// ***********************************
			if (i > 0)
			{
				// RTL Name: ap_return
				{
					// bitslice(31, 0)
					// {
						// celement: return(31, 0)
						// {
							sc_lv<32> return_lv0_0_1_0;
						// }
					// }

					// bitslice(31, 0)
					{
						// celement: return(31, 0)
						{
							// carray: (0) => (1) @ (0)
							{
								if (&(AESL_return) != NULL) // check the null address if the c port is array or others
								{
									return_lv0_0_1_0.range(31, 0) = sc_bv<32>(ap_return_pc_buffer.range(31, 0));
								}
							}
						}
					}

					// bitslice(31, 0)
					{
						// celement: return(31, 0)
						{
							// carray: (0) => (1) @ (0)
							{
								// sub                    : 
								// ori_name               : AESL_return
								// sub_1st_elem           : 
								// ori_name_1st_elem      : AESL_return
								// output_left_conversion : AESL_return
								// output_type_conversion : (return_lv0_0_1_0).to_uint64()
								if (&(AESL_return) != NULL) // check the null address if the c port is array or others
								{
									AESL_return = (return_lv0_0_1_0).to_uint64();
								}
							}
						}
					}
				}
			}
		}

		AESL_transaction_pc++;

		return AESL_return;
	}
	else
	{
		CodeState = ENTER_WRAPC;
		static unsigned AESL_transaction;

		static AESL_FILE_HANDLER aesl_fh;

		// "alphabuf"
		char* tvin_alphabuf = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_alphabuf);

		// "intensity"
		char* tvin_intensity = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_intensity);

		// "node_output"
		char* tvin_node_output = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_node_output);
		char* tvout_node_output = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_node_output);

		// "node_count"
		char* tvin_node_count = new char[50];
		aesl_fh.touch(AUTOTB_TVIN_node_count);
		char* tvout_node_count = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_node_count);

		// "ap_return"
		char* tvout_ap_return = new char[50];
		aesl_fh.touch(AUTOTB_TVOUT_ap_return);

		CodeState = DUMP_INPUTS;
		static INTER_TCL_FILE tcl_file(INTER_TCL);
		int leading_zero;

		// [[transaction]]
		sprintf(tvin_alphabuf, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_alphabuf, tvin_alphabuf);

		sc_bv<32>* alphabuf_tvin_wrapc_buffer = new sc_bv<32>[16];

		// RTL Name: alphabuf
		{
			// bitslice(31, 0)
			{
				int hls_map_index = 0;
				// celement: alphabuf(31, 0)
				{
					// carray: (0) => (3) @ (1)
					for (int i_0 = 0; i_0 <= 3; i_0 += 1)
					{
						// carray: (0) => (3) @ (1)
						for (int i_1 = 0; i_1 <= 3; i_1 += 1)
						{
							// sub                   : i_0 i_1
							// ori_name              : alphabuf[i_0][i_1]
							// sub_1st_elem          : 0 0
							// ori_name_1st_elem     : alphabuf[0][0]
							// regulate_c_name       : alphabuf
							// input_type_conversion : alphabuf[i_0][i_1]
							if (&(alphabuf[0][0]) != NULL) // check the null address if the c port is array or others
							{
								sc_lv<32> alphabuf_tmp_mem;
								alphabuf_tmp_mem = alphabuf[i_0][i_1];
								alphabuf_tvin_wrapc_buffer[hls_map_index++].range(31, 0) = alphabuf_tmp_mem.range(31, 0);
							}
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 16; i++)
		{
			sprintf(tvin_alphabuf, "%s\n", (alphabuf_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_alphabuf, tvin_alphabuf);
		}

		tcl_file.set_num(16, &tcl_file.alphabuf_depth);
		sprintf(tvin_alphabuf, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_alphabuf, tvin_alphabuf);

		// release memory allocation
		delete [] alphabuf_tvin_wrapc_buffer;

		// [[transaction]]
		sprintf(tvin_intensity, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_intensity, tvin_intensity);

		sc_bv<16> intensity_tvin_wrapc_buffer;

		// RTL Name: intensity
		{
			// bitslice(15, 0)
			{
				// celement: intensity(15, 0)
				{
					// carray: (0) => (0) @ (0)
					{
						// sub                   : 
						// ori_name              : intensity
						// sub_1st_elem          : 
						// ori_name_1st_elem     : intensity
						// regulate_c_name       : intensity
						// input_type_conversion : intensity
						if (&(intensity) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<16> intensity_tmp_mem;
							intensity_tmp_mem = intensity;
							intensity_tvin_wrapc_buffer.range(15, 0) = intensity_tmp_mem.range(15, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvin_intensity, "%s\n", (intensity_tvin_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_intensity, tvin_intensity);
		}

		tcl_file.set_num(1, &tcl_file.intensity_depth);
		sprintf(tvin_intensity, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_intensity, tvin_intensity);

		// [[transaction]]
		sprintf(tvin_node_output, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_node_output, tvin_node_output);

		sc_bv<32>* node_output_tvin_wrapc_buffer = new sc_bv<32>[16];

		// RTL Name: node_output
		{
			// bitslice(31, 0)
			{
				int hls_map_index = 0;
				// celement: node_output(31, 0)
				{
					// carray: (0) => (3) @ (1)
					for (int i_0 = 0; i_0 <= 3; i_0 += 1)
					{
						// carray: (0) => (3) @ (1)
						for (int i_1 = 0; i_1 <= 3; i_1 += 1)
						{
							// sub                   : i_0 i_1
							// ori_name              : node_output[i_0][i_1]
							// sub_1st_elem          : 0 0
							// ori_name_1st_elem     : node_output[0][0]
							// regulate_c_name       : node_output
							// input_type_conversion : node_output[i_0][i_1]
							if (&(node_output[0][0]) != NULL) // check the null address if the c port is array or others
							{
								sc_lv<32> node_output_tmp_mem;
								node_output_tmp_mem = node_output[i_0][i_1];
								node_output_tvin_wrapc_buffer[hls_map_index++].range(31, 0) = node_output_tmp_mem.range(31, 0);
							}
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 16; i++)
		{
			sprintf(tvin_node_output, "%s\n", (node_output_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_node_output, tvin_node_output);
		}

		tcl_file.set_num(16, &tcl_file.node_output_depth);
		sprintf(tvin_node_output, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_node_output, tvin_node_output);

		// release memory allocation
		delete [] node_output_tvin_wrapc_buffer;

		// [[transaction]]
		sprintf(tvin_node_count, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVIN_node_count, tvin_node_count);

		sc_bv<32>* node_count_tvin_wrapc_buffer = new sc_bv<32>[16];

		// RTL Name: node_count
		{
			// bitslice(31, 0)
			{
				int hls_map_index = 0;
				// celement: node_count(31, 0)
				{
					// carray: (0) => (3) @ (1)
					for (int i_0 = 0; i_0 <= 3; i_0 += 1)
					{
						// carray: (0) => (3) @ (1)
						for (int i_1 = 0; i_1 <= 3; i_1 += 1)
						{
							// sub                   : i_0 i_1
							// ori_name              : node_count[i_0][i_1]
							// sub_1st_elem          : 0 0
							// ori_name_1st_elem     : node_count[0][0]
							// regulate_c_name       : node_count
							// input_type_conversion : node_count[i_0][i_1]
							if (&(node_count[0][0]) != NULL) // check the null address if the c port is array or others
							{
								sc_lv<32> node_count_tmp_mem;
								node_count_tmp_mem = node_count[i_0][i_1];
								node_count_tvin_wrapc_buffer[hls_map_index++].range(31, 0) = node_count_tmp_mem.range(31, 0);
							}
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 16; i++)
		{
			sprintf(tvin_node_count, "%s\n", (node_count_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVIN_node_count, tvin_node_count);
		}

		tcl_file.set_num(16, &tcl_file.node_count_depth);
		sprintf(tvin_node_count, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVIN_node_count, tvin_node_count);

		// release memory allocation
		delete [] node_count_tvin_wrapc_buffer;

// [call_c_dut] ---------->

		CodeState = CALL_C_DUT;
		int AESL_return = AESL_ORIG_DUT_assign_intensity(alphabuf, intensity, node_output, node_count);

		CodeState = DUMP_OUTPUTS;

		// [[transaction]]
		sprintf(tvout_node_output, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_node_output, tvout_node_output);

		sc_bv<32>* node_output_tvout_wrapc_buffer = new sc_bv<32>[16];

		// RTL Name: node_output
		{
			// bitslice(31, 0)
			{
				int hls_map_index = 0;
				// celement: node_output(31, 0)
				{
					// carray: (0) => (3) @ (1)
					for (int i_0 = 0; i_0 <= 3; i_0 += 1)
					{
						// carray: (0) => (3) @ (1)
						for (int i_1 = 0; i_1 <= 3; i_1 += 1)
						{
							// sub                   : i_0 i_1
							// ori_name              : node_output[i_0][i_1]
							// sub_1st_elem          : 0 0
							// ori_name_1st_elem     : node_output[0][0]
							// regulate_c_name       : node_output
							// input_type_conversion : node_output[i_0][i_1]
							if (&(node_output[0][0]) != NULL) // check the null address if the c port is array or others
							{
								sc_lv<32> node_output_tmp_mem;
								node_output_tmp_mem = node_output[i_0][i_1];
								node_output_tvout_wrapc_buffer[hls_map_index++].range(31, 0) = node_output_tmp_mem.range(31, 0);
							}
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 16; i++)
		{
			sprintf(tvout_node_output, "%s\n", (node_output_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_node_output, tvout_node_output);
		}

		tcl_file.set_num(16, &tcl_file.node_output_depth);
		sprintf(tvout_node_output, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_node_output, tvout_node_output);

		// release memory allocation
		delete [] node_output_tvout_wrapc_buffer;

		// [[transaction]]
		sprintf(tvout_node_count, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_node_count, tvout_node_count);

		sc_bv<32>* node_count_tvout_wrapc_buffer = new sc_bv<32>[16];

		// RTL Name: node_count
		{
			// bitslice(31, 0)
			{
				int hls_map_index = 0;
				// celement: node_count(31, 0)
				{
					// carray: (0) => (3) @ (1)
					for (int i_0 = 0; i_0 <= 3; i_0 += 1)
					{
						// carray: (0) => (3) @ (1)
						for (int i_1 = 0; i_1 <= 3; i_1 += 1)
						{
							// sub                   : i_0 i_1
							// ori_name              : node_count[i_0][i_1]
							// sub_1st_elem          : 0 0
							// ori_name_1st_elem     : node_count[0][0]
							// regulate_c_name       : node_count
							// input_type_conversion : node_count[i_0][i_1]
							if (&(node_count[0][0]) != NULL) // check the null address if the c port is array or others
							{
								sc_lv<32> node_count_tmp_mem;
								node_count_tmp_mem = node_count[i_0][i_1];
								node_count_tvout_wrapc_buffer[hls_map_index++].range(31, 0) = node_count_tmp_mem.range(31, 0);
							}
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 16; i++)
		{
			sprintf(tvout_node_count, "%s\n", (node_count_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_node_count, tvout_node_count);
		}

		tcl_file.set_num(16, &tcl_file.node_count_depth);
		sprintf(tvout_node_count, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_node_count, tvout_node_count);

		// release memory allocation
		delete [] node_count_tvout_wrapc_buffer;

		// [[transaction]]
		sprintf(tvout_ap_return, "[[transaction]] %d\n", AESL_transaction);
		aesl_fh.write(AUTOTB_TVOUT_ap_return, tvout_ap_return);

		sc_bv<32> ap_return_tvout_wrapc_buffer;

		// RTL Name: ap_return
		{
			// bitslice(31, 0)
			{
				// celement: return(31, 0)
				{
					// carray: (0) => (1) @ (0)
					{
						// sub                   : 
						// ori_name              : AESL_return
						// sub_1st_elem          : 
						// ori_name_1st_elem     : AESL_return
						// regulate_c_name       : return
						// input_type_conversion : AESL_return
						if (&(AESL_return) != NULL) // check the null address if the c port is array or others
						{
							sc_lv<32> return_tmp_mem;
							return_tmp_mem = AESL_return;
							ap_return_tvout_wrapc_buffer.range(31, 0) = return_tmp_mem.range(31, 0);
						}
					}
				}
			}
		}

		// dump tv to file
		for (int i = 0; i < 1; i++)
		{
			sprintf(tvout_ap_return, "%s\n", (ap_return_tvout_wrapc_buffer).to_string(SC_HEX).c_str());
			aesl_fh.write(AUTOTB_TVOUT_ap_return, tvout_ap_return);
		}

		tcl_file.set_num(1, &tcl_file.ap_return_depth);
		sprintf(tvout_ap_return, "[[/transaction]] \n");
		aesl_fh.write(AUTOTB_TVOUT_ap_return, tvout_ap_return);

		CodeState = DELETE_CHAR_BUFFERS;
		// release memory allocation: "alphabuf"
		delete [] tvin_alphabuf;
		// release memory allocation: "intensity"
		delete [] tvin_intensity;
		// release memory allocation: "node_output"
		delete [] tvin_node_output;
		delete [] tvout_node_output;
		// release memory allocation: "node_count"
		delete [] tvin_node_count;
		delete [] tvout_node_count;
		// release memory allocation: "ap_return"
		delete [] tvout_ap_return;

		AESL_transaction++;

		tcl_file.set_num(AESL_transaction , &tcl_file.trans_num);

		return AESL_return;
	}
}

